project_path: &project_path /home/jdwang/PycharmProjects/weiboStanceDetection/cnn/dcnn
date: &date '20160623'

#------------------------------------- dcnn ----------------------------------------------
dcnn:
    path: /home/jdwang/PycharmProjects/weiboStanceDetection/cnn/dcnn/dcnn.py
  
    # 描述
    describe: 

    name: &name RandEmbeddingCNN

    train_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/train_data_%s_2090.csv
#    train_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/train_data_half_2090.csv
    test_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/test_data_%s_896.csv

    train_data_type: &train_data_type full
    test_data_type: &test_data_type full

#    1=2090,2=5087,3=weibo,4=20963
    word2vec_type: &word2vec_type '4'

#    word2vec_file_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/train_data_full_2090_%ddim.gem
#    word2vec_file_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/train_data_full_5087_%ddim.gem
#    word2vec_file_path: /home/jdwang/PycharmProjects/corprocessor/word2vec/vector/vector1000000_%ddim.gem
    word2vec_file_path: /home/jdwang/PycharmProjects/weiboStanceDetection/data_processing/word2vec/vector/train_data_full_20963_%ddim_50iter_cbow.gem

    refresh_all_model: False

    verbose: 1

    need_segmented: True

    sentence_padding_length: &sentence_padding_length 50
    word_embedding_dim: &word_embedding_dim 32


    conv_filter_type: [
                        [100,2,*word_embedding_dim,'valid'],
                        [100,4,*word_embedding_dim,'valid'],
                        # [100,6,*word_embedding_dim,'valid'],
                        [100,8,*word_embedding_dim,'valid'],
                        # [100,10,*word_embedding_dim,'valid'],
                      ]
    kmax_k: 1

    cnn_nb_epoch: &cnn_nb_epoch '200'

    earlyStoping_patience: 150

    embedding_dropout_rate: 0.5

    output_dropout_rate: 0.5

    model_file_path: &model_file_path [*project_path,'/model/',*date,'_',*name,'_',*sentence_padding_length,'len_',*word_embedding_dim,'dim_',*train_data_type,'train_',*word2vec_type,'pre_',*cnn_nb_epoch,'epoch.pkl']


    log_file_path: [*project_path,'/log/',*date,'_',*name,'.log']
  
    result_file_path: [*project_path,'/result/',*date,'_',*name,'.csv']