project_path: &project_path /home/jdwang/PycharmProjects/weiboStanceDetection/cue_pharse
date: &date '20160630'

#------------------------------------- cue_pharse ----------------------------------------------
cue_pharse:
    path: /home/jdwang/PycharmProjects/weiboStanceDetection/cue_pharse/cue_pharse.py
  
    # 描述
    describe: 

    name: &name cue_pharse
  
    verbose: 1

    log_file_path: [*project_path,'/log/',*date,'_',*name,'.log']
  
    result_file_path: [*project_path,'/result/',*date,'_',*name,'.csv']