project_path: &project_path /home/jdwang/PycharmProjects/weiboStanceDetection/cnn/randEmbedding_cnn
date: &date '20160623'

#------------------------------------- RandEmbeddingCNN ----------------------------------------------
randEmbedding_cnn:
    path: /home/jdwang/PycharmProjects/weiboStanceDetection/cnn/randEmbedding_cnn/randEmbedding_cnn.py
  
    # 描述
    describe: 

    name: &name RandEmbeddingCNN

    train_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/TaskAA_train_data_%s_2090.csv
#    train_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/train_data_half_2090.csv
#    test_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/test_data_896.csv
    test_data_filte_path: /home/jdwang/PycharmProjects/weiboStanceDetection/train_data/TaskAA_test_data_%s_896.csv

#    train_data_type: &train_data_type Mhalf
    train_data_type: &train_data_type full
    test_data_type: &test_data_type Mhalf

    refresh_all_model: False
#    是否生成cnn深度特征
    genernate_cnn_feature: False

#    rand_seed: [0,100,400,600,800,1000]
    rand_seed: [1000]

    verbose: 2

    need_segmented: True

    sentence_padding_length: &sentence_padding_length 93
    word_embedding_dim: &word_embedding_dim 300


    conv_filter_type: [
                        [100,2,*word_embedding_dim,'valid'],
                        [100,4,*word_embedding_dim,'valid'],
                        # [100,6,*word_embedding_dim,'valid'],
                        [100,8,*word_embedding_dim,'valid'],
                        # [100,10,*word_embedding_dim,'valid'],
                      ]

    kmax_k: &kmax_k 1

    cnn_nb_epoch: &cnn_nb_epoch 30

    optimizers: &optimizers adadelta

    earlyStoping_patience: 50

    embedding_dropout_rate: 0.5

    output_dropout_rate: 0.5

    model_file_path: &model_file_path [*project_path,'/model/',*name,'_',*optimizers,'_',*sentence_padding_length,'len_',*word_embedding_dim,'dim_',*kmax_k,'k_',*train_data_type,'train_',*cnn_nb_epoch,'epoch_%dseed.pkl']

    train_cnn_feature_file_path: [*project_path,'/feature/train_',*name,'_',*optimizers,'_',*sentence_padding_length,'len_',*word_embedding_dim,'dim_',*kmax_k,'k_',*train_data_type,'train_',*cnn_nb_epoch,'epoch_%dseed.npy']
    test_cnn_feature_file_path: [*project_path,'/feature/test_',*name,'_',*optimizers,'_',*sentence_padding_length,'len_',*word_embedding_dim,'dim_',*kmax_k,'k_',*train_data_type,'train_',*cnn_nb_epoch,'epoch_%dseed.npy']


    log_file_path: [*project_path,'/log/',*date,'_',*name,'.log']
  
    result_file_path: [*project_path,'/result/',*name,'_',*optimizers,'_',*sentence_padding_length,'len_',*word_embedding_dim,'dim_',*kmax_k,'k_',*train_data_type,'train_',*cnn_nb_epoch,'epoch_%dseed.csv']